import type { Metadata } from "next";
import { Inter, Philosopher, Quattrocento_Sans } from "next/font/google";
import "./globals.css";
// import AppHeader from "@/components/library/commonSections/Header";
import { fetchCommonSection } from "@/services/strapiService";
import { CommonSectionsProvider } from "@/context/CommonSectionsContext";
// import dynamic from "next/dynamic";
import React from "react";
import GoogleAnalytics from "@/lib/GoogleAnalytics";

// const AppFooter = dynamic(
//   () => import("@/components/library/commonSections/Footer")
// );

export const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  display: "swap",
  variable: "--font-inter",
});

export const philosopher = Philosopher({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-philosopher",
});
export const quattrocentoSans = Quattrocento_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-quatSans",
});

export const metadata: Metadata = {
  title: "Nooora Beauty Concierge",
  description: "Generated by create next app",
  icons: "/favicon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const commonSectionsDataPormise = fetchCommonSection();

  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${philosopher.variable} ${quattrocentoSans.variable} antialiased`}
      >
        <GoogleAnalytics />
        {/* <AppHeader headerData={commonSectionsData.header} /> */}
        <CommonSectionsProvider fetchPromise={commonSectionsDataPormise}>
          {children}
        </CommonSectionsProvider>
        {/* <AppFooter footerData={commonSectionsData.footer} /> */}
      </body>
    </html>
  );
}
